.nh
.TH "GH-ATTESTATION" "1" "Jul 2024" "GitHub CLI 2.53.0" "GitHub CLI manual"

.SH NAME
.PP
gh-attestation - Work with artifact attestations


.SH SYNOPSIS
.PP
\fBgh attestation [subcommand] [flags]\fR


.SH DESCRIPTION
.PP
Download and verify artifact attestations.


.SH AVAILABLE COMMANDS
.TP
\fBgh-attestation-download(1)\fR
Download an artifact's attestations for offline use

.TP
\fBgh-attestation-trusted-root(1)\fR
Output trusted_root.jsonl contents, likely for offline verification

.TP
\fBgh-attestation-verify(1)\fR
Verify an artifact's integrity using attestations


.SH ALIASES
.PP
gh at


.SH SEE ALSO
.PP
\fBgh(1)\fR
